### ISSUE TITLE
Bearer token deserializer should not log invalid tokens

### ISSUE THREAD

**Issue by mgelmi** [palantir/auth-tokens#13]
in file: https://github.com/palantir/auth-tokens/blob/develop/auth-tokens/src/main/java/com/palantir/tokens/auth/BearerToken.java#L43

**Comment by ash211** [comment]
Why should this log be taken out?  It's very helpful with debugging, and because it's only logging _invalid_ tokens the logged value generally can't be used by the log viewer to get permissions to something they shouldn't have.

**Comment by NeilRickards** [comment]
Request originally came from @leeavital who accidentally copied two valid tokens into a CURL request, and was disturbed to see them in the server logs

**Comment by pnepywoda** [comment]
I don't understand - BearerToken isn't logging invalid tokens, it's DISALLOWing invalid tokens (throwing an exception). Throwing an exception is what I'd expect when you give a token that doesn't conform to the syntax spec

**Comment by ghost** [comment]
AppSec here:

You could imagine someone fat-fingers a paste and includes some whitespace, or mistakenly includes `Bearer`, or mistakenly urlencodes, or anything else that could make an otherwise valid token fail this check.

I would not expect the caller of `BearerToken.valueOf()` to catch the IllegalArgumentException thrown by Guava, but I would expect (and hope) that its message is logged somewhere up the stack.

I think it's reasonable, and preferable, to not throw unchecked exceptions whose messages might contain potentially sensitive information, and that we should remove `+ token` from the message string.

**Comment by markelliot** [comment]
Resolved in #20.
